user = User.create!(username: "alycit", name: "Alyssa", password: "123456")

Game.create!(name: "Monopoly", user: user)
Game.create!(name: "Scrabble", user: user)
Game.create!(name: "Hanabi", user: user)
Game.create!(name: "Billionaire Banshee", user: user)
Game.create!(name: "Fluxx", user: user)
Game.create!(name: "Boggle", user: user)
Game.create!(name: "Magic", user: user)
Game.create!(name: "Risk", user: user)
Game.create!(name: "Blokus", user: user)
Game.create!(name: "Saboteur", user: user)